name: auto-close-milestone

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: run
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: result
        run: echo ${{ steps.run.outputs.milestones }}